### ISSUE TITLE
Lost groups

### ISSUE THREAD

**Issue by fenixfe** [Morikko/synctabgroups.github.io#6]
Hi there. I updated firefox (now on 115.6.0esr) and a new firefox profile was created. 

All my groups were lost, which for my workflow is quite a catastrophe :(  Unfortunately my newest backup is three months old and I would like to know if there is another option to restore my groups to a newer version. 

Can I find the groups saved somewhere in my old firefox profile and import them? 

I hope you can help me! 
Thanks a lot!

**Comment by Morikko** [comment]
Normally yes: https://github.com/Morikko/sync-tab-groups/wiki/Backup#internal-backup-location

**Comment by Morikko** [comment]
You may have to adapt the path if your profile is not default but using random characters. Sync Tab Groups is stopped so I would recommend to switch to another extension.

See: https://github.com/Morikko/sync-tab-groups#the-project-is-no-more-maintained

**Comment by fenixfe** [comment]
Thanks Morikko for your quick reply. I will follow your advice and change to another extension, but I still hope to recover my groups. The path you suggested does contain a file called "storage.js.migrated" , but replacing it doesn't change anything. The tab groups are still empty...!

I just remembered, there was a sort of crash  before the groups were lost, and there is a crash log callecd "SyncTabGroups-Log-20240116-235052" ... would that be of any help?

**Comment by Morikko** [comment]
I do not fully remember how the firefox local storage works, but it is delegated to the browser. You may look into this file with a text editor to see if it seems to contain yours groups. You should also check there is no other profile.

The `.migrated` looks suspicious, you may try to use the file without that extension. But be careful, I have no guarantee the extension is still working on current Firefox version, you may also give it a try on a older version in case of. Backup your data and do your testing in a testing firefox profile, not your current one.

Logs files are not useful as they contain no group information.
